version: "3"
services:
  mysql_db:
    image: mysql:5.7
    ports:
      - 8306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_pwd_336699
    volumes:
      - ./docker/data/mysql/:/var/lib/mysql
    restart: always
    networks:
      - app
    command: [mysqld,--general_log=ON,--general_log_file=mysql.common.log,--slow-query-log=ON,--slow_query_log_file=mysql.slow.log, --sql-mode=NO_ENGINE_SUBSTITUTION, --character-set-server=utf8, --collation-server=utf8_general_ci]
networks:
  app:
    external: true