version: '2'
services:
  node:
    image: haproxy:1.5
    restart: always
    network_mode: "host"
    volumes:
      - ./docker-data/certs:/certs
      - /dev/log:/dev/log
      - ./docker-data/config:/usr/local/etc/haproxy:ro
    ports:
      - 80:80
      - 443:443
  mock:
    container_name: mock
    image: sanfun/public:nginx-php7-alpine-v12
    restart: always
    network_mode: "host"
    volumes:
      - ./docker-data/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker-data/config/supervisord.conf:/etc/supervisord.conf:ro
      - ./pt-mock/wwwroot:/var/www/html
      - ./docker-data:/docker-data
